### ISSUE TITLE
incomplete logic of library usage

### ISSUE THREAD

**Issue by olehsamoilenko** [omiroshn/Wolf3dSDL#1]
Generally, it's not an issue, but there is a way to improve this part of Makefile.

Technically you are assuming that if your system is linux then sdl2 is installed. It's not true for me and for many other linuxes:)

```Makefile
ifeq ($(OS), Linux)
CGFLAGS = `sdl2-config --cflags --libs` -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lm
else
CGFLAGS = -framework OpenGL -framework AppKit
INCLUDES =         -I./frameworks/SDL2.framework/Versions/A/Headers \
                              -I./frameworks/SDL2_ttf.framework/Versions/A/Headers \
		              -I./frameworks/SDL2_image.framework/Versions/A/Headers \
		              -I./frameworks/SDL2_mixer.framework/Headers \
		              -F./frameworks/
FRAMEWORKS = -F./frameworks \
			      -rpath ./frameworks \
			      -framework OpenGL -framework AppKit -framework OpenCl \
			      -framework SDL2 -framework SDL2_ttf -framework SDL2_image \
			      -framework SDL2_mixer
endif
```
Why not to use the library you are carrying with the project?

Personally, I see 2 different ways of Makefile improvement:
* use a single local library for linux and mac-os
* change a condition to something like:
```Makefile
ifneq ($(whereis libsdl2-dev), "") # test example, not tested
```
to make sure that lib is installed

Finally, it's not a bug or an issue, but a way of build process improvement.
Have a good day, thanks.

**Comment by lighth7015** [comment]
lol, that's not exactly what I'd call "incomplete". And you're a linux distribution? I think you meant to say, it's not true for your linux distro. :p

Anyway, if you're running linux, you're expected to know how to install dependencies. It's not that difficult. :p
